# Generated by Django 4.0.4 on 2022-05-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Login',
        ),
    ]
